"""changes

Revision ID: 112614015dae
Revises: 8734f699410f
Create Date: 2022-11-25 05:49:45.461208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112614015dae'
down_revision = '8734f699410f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
